version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking Docker version...
      - docker --version
      - DATE_TAG=$(date '+%Y%m%d-%H%M')
      - IMAGE_TAG=latest
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 223647876635.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=223647876635.dkr.ecr.ap-south-1.amazonaws.com/test
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:${DATE_TAG}-${IMAGE_TAG} --file Dockerfile .
      - docker tag $REPOSITORY_URI:${DATE_TAG}-${IMAGE_TAG} $REPOSITORY_URI:${DATE_TAG}-${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:${DATE_TAG}-${IMAGE_TAG}
      - echo Pushed Docker image successfully
      - echo Writing image definitions file...
      - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $REPOSITORY_URI:${DATE_TAG}-${IMAGE_TAG} > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
